spring:
    profiles:
        active: local

---

spring:
    profiles: local
    thymeleaf.cache: false
    devtools:
        livereload.enabled: true
        restart.enabled: true
    jpa:
        hibernate.ddl-auto: update
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    datasource:
        url: jdbc:mysql://localhost:3306/wootecobook?serverTimezone=UTC
        username: zzinbros
        password: 1234
    output.ansi.enabled: detect

logging:
    level:
        root: INFO
        com.woowacourse.zzinbros: DEBUG

logback.access:
    enabled: true
    config: "classpath:logback-access.xml"

zzinbros:
    uploadto:
        strategy: s3
        uploadurl: zzinbros/images
        downloadurl: https://zzinbros.s3.ap-northeast-2.amazonaws.com/images/

---

spring:
    profiles: test
    thymeleaf.cache: false
    jpa:
        hibernate.ddl-auto: create-drop
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true
    datasource:
        url: jdbc:h2:mem:test
        username: sa
        password: sa
        driver-class-name: org.h2.Driver
    output.ansi.enabled: detect

logging:
    level:
        root: WARN
        com.woowacourse.zzinbros: DEBUG

zzinbros:
    uploadto:
        strategy: s3
        uploadurl: zzinbros/images
        downloadurl: https://zzinbros.s3.ap-northeast-2.amazonaws.com/images/

---

spring:
    profiles: deploy
    jpa:
        hibernate.ddl-auto: update
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
        url: jdbc:mysql://localhost:3306/wootecobook?serverTimezone=UTC
        username: zzinbros
        password: 1234
    output.ansi.enabled: detect

logging:
    level:
        root: WARN
        com.woowacourse.zzinbros: INFO
    file.max-history: 30

zzinbros:
    uploadto:
        strategy: s3
        uploadurl: zzinbros/images
        downloadurl: https://zzinbros.s3.ap-northeast-2.amazonaws.com/images/